### ISSUE TITLE
LocalTestServer without external dependencies for server side functions

### ISSUE THREAD

**Issue by shoyer** [pydap/pydap#119]
I just experimented a little with using Pydap's new `LocalTestServer` feature for xarray. This looks great, but using it requires server side functions, which adds two additional dependencies for pydap -- gsw and coords.

For a local test setup (e.g., for verifying that pydap is working correctly with xarray), ideally we could make things work with just pydap.

**Comment by rabernat** [comment]
I just started playing with pydap and hit this same issue.

It would be nice to have an easy way to bypass these server side functions from the command line, or simply not apply them if the dependencies are not available.

```
Traceback (most recent call last):
  File "/Users/rpa/Code/pydap/src/pydap/lib.py", line 286, in load_from_entry_point_relative
    globals(), None, [r.attrs[0]], 1),
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/functions.py", line 28, in <module>
    import gsw
ModuleNotFoundError: No module named 'gsw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/app.py", line 184, in __call__
    return req.get_response(self.app)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/request.py", line 1327, in send
    application, catch_exc_info=False)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/request.py", line 1291, in call_application
    app_iter = application(self.environ, start_response)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/app.py", line 86, in __call__
    app = ServerSideFunctions(get_handler(base, self.handlers))
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/ssf.py", line 58, in __init__
    self.functions = load_functions()
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/ssf.py", line 36, in load_functions
    for r in iter_entry_points(entry_points)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/ssf.py", line 37, in <genexpr>
    if r.module_name.startswith(package))
  File "/Users/rpa/Code/pydap/src/pydap/lib.py", line 291, in load_from_entry_point_relative
    return r.name, r.load()
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/functions.py", line 28, in <module>
    import gsw
ModuleNotFoundError: No module named 'gsw'
[2018-03-17 15:11:23 -0400] [37549] [ERROR] Error handling request /nino34_index.nc.html
Traceback (most recent call last):
  File "/Users/rpa/Code/pydap/src/pydap/lib.py", line 286, in load_from_entry_point_relative
    globals(), None, [r.attrs[0]], 1),
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/functions.py", line 28, in <module>
    import gsw
ModuleNotFoundError: No module named 'gsw'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/app.py", line 184, in __call__
    return req.get_response(self.app)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/request.py", line 1327, in send
    application, catch_exc_info=False)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/request.py", line 1291, in call_application
    app_iter = application(self.environ, start_response)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 131, in __call__
    resp = self.call_func(req, *args, **self.kwargs)
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/webob/dec.py", line 196, in call_func
    return self.func(req, *args, **kwargs)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/app.py", line 86, in __call__
    app = ServerSideFunctions(get_handler(base, self.handlers))
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/ssf.py", line 58, in __init__
    self.functions = load_functions()
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/ssf.py", line 36, in load_functions
    for r in iter_entry_points(entry_points)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/ssf.py", line 37, in <genexpr>
    if r.module_name.startswith(package))
  File "/Users/rpa/Code/pydap/src/pydap/lib.py", line 291, in load_from_entry_point_relative
    return r.name, r.load()
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/Users/rpa/miniconda3/envs/pangeo_pydap/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/rpa/Code/pydap/src/pydap/wsgi/functions.py", line 28, in <module>
    import gsw
ModuleNotFoundError: No module named 'gsw'
```
