### ISSUE TITLE
ASCII response error

### ISSUE THREAD

**Issue by jblarsen** [pydap/pydap#157]
When I try this request (I run pydap on port 8090):

```
http://localhost:8090/test.nc.ascii?time[0]
```

I get an error:

```
[2018-01-04 16:00:26 +0100] [26105] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/jla/pydap/pydap/src/pydap/model.py", line 235, in __getattr__
    return self.attributes[attr]
KeyError: 'flat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jla/pydap/lib/python3.5/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
  File "/home/jla/pydap/pydap/src/pydap/responses/ascii.py", line 42, in __iter__
    for line in ascii(self.dataset):
  File "/home/jla/pydap/pydap/src/pydap/responses/ascii.py", line 71, in _structuretype
    for line in ascii(child, printname):
  File "/home/jla/pydap/pydap/src/pydap/responses/ascii.py", line 85, in _basetype
    for indexes, value in zip(np.ndindex(var.shape), var.data.flat):
  File "/home/jla/pydap/pydap/src/pydap/model.py", line 239, in __getattr__
    % (type(self), attr))
AttributeError: '<class 'pydap.model.BaseType'>' object has no attribute 'flat'
```

The NetCDF file I try to request is a test file with the following CDL (use ncgen to create the NetCDF file):

```
netcdf test {
dimensions:
	lat = 2 ;
	lon = 2 ;
	time = UNLIMITED ; // (4 currently)
variables:
	float lat(lat) ;
		lat:units = "degrees_north" ;
	float lon(lon) ;
		lon:units = "degrees_east" ;
	double time(time) ;
		time:units = "hours since 2017-01-01 00:00:00.0" ;
		time:calendar = "standard" ;
	float var_const(time, lat, lon) ;
		var_const:_FillValue = 9.96921e+36f ;
		var_const:long_name = "test long_name" ;
		var_const:units = "test units" ;

// global attributes:
		:_NCProperties = "version=1|netcdflibversion=4.4.1.1|hdf5libversion=1.8.18" ;
		:history = "Thu Jan  4 16:08:40 2018: ncks -d lat,0,1 -d lon,0,1 -d time,0,3 test.nc test2.nc" ;
		:NCO = "\"4.5.4\"" ;
data:

 lat = -70, -60 ;

 lon = 0, 10 ;

 time = 0, 1, 2, 3 ;

 var_const =
  10, 10,
  10, 10,
  10, 10,
  10, 10,
  10, 10,
  10, 10,
  10, 10,
  10, 10 ;
}
```

This request works fine:

```
http://localhost:8090/test.nc.ascii?time
```

I have used pydap from the master branch which has a NetCDF handler included. But I had to do this:

https://github.com/pydap/pydap/issues/129

to get it registered before installing pydap.

I have done some investigations. It seems like the response gets some nested BaseType objects and that it cannot handle these. But I am not entirely sure whether it is an issue with the response or the application of the constraint on BaseTypes.

**Comment by jblarsen** [comment]
I believe that this issue is related to #132

**Comment by jblarsen** [comment]
Here is a suggestion for a fix based on the dods response:

```
$ git diff
diff --git a/src/pydap/responses/ascii.py b/src/pydap/responses/ascii.py
index fb89bd5..48c054c 100644
--- a/src/pydap/responses/ascii.py
+++ b/src/pydap/responses/ascii.py
@@ -82,7 +82,8 @@ def _basetype(var, printname=True):
     if not getattr(var, "shape", ()):
         yield encode(var.data)
     else:
-        for indexes, value in zip(np.ndindex(var.shape), var.data.flat):
-            yield "{indexes} {value}\n".format(
-                indexes="[" + "][".join([str(idx) for idx in indexes]) + "]",
-                value=encode(value))
+        for block in var.data:
+            for indexes, value in zip(np.ndindex(block.shape), block.flat):
+                yield "{indexes} {value}\n".format(
+                    indexes="[" + "][".join([str(idx) for idx in indexes]) + "]",
+                    value=encode(value))
```
