### ISSUE TITLE
Remove / deprecate NCA and CDMS handlers from handlers documentation?

### ISSUE THREAD

**Issue by evertrol** [pydap/pydap#183]
The `pydap.handlers.nca` and `pydap.handlers.cdms` handlers are still listed on the [handlers documentation](http://pydap.org/en/latest/handlers.html), but these packages are not Python 3 compatible. Further, their latest release on PyPI are from 2012 and 2011, respectively.

Perhaps these handlers should be removed from the documentation, or be marked as deprecated/outdated and unusable with Python 3?

**Comment by evertrol** [comment]
Actually, this appears to be the case for the NetCDF and HDF5 handlers as well: I can't install these from PyPI with `pip3`, since these packages are not Python 3 compatible. Am I overlooking something?

Example error:

```shell
$ pip3 install pydap.handlers.netcdf

Collecting pydap.handlers.netcdf
  Downloading https://files.pythonhosted.org/packages/33/a3/994079b67cadb9db6972a64d6790f37113dcff1778be4f3ba5225aad5f11/pydap.handlers.netcdf-0.6.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-gy_a8_c4/pydap.handlers.netcdf/setup.py", line 6, in <module>
        import paver.tasks
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 906, in _find_spec
      File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
      File "<frozen importlib._bootstrap_external>", line 1254, in _get_spec
      File "<frozen importlib._bootstrap_external>", line 1235, in _legacy_get_spec
      File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
      File "<frozen importlib._bootstrap_external>", line 594, in spec_from_file_location
      File "paver-minilib.zip/paver/tasks.py", line 69
        print output
                   ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(output)?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/98/hvxclx6x37b439367dr019t80000gn/T/pip-install-gy_a8_c4/pydap.handlers.netcdf/
```

**Comment by flackdl** [comment]
I am running into the same issue.
