### ISSUE TITLE
Large-ish files don't get properly served

### ISSUE THREAD

**Issue by evertrol** [pydap/pydap#184]
I'm trying the stand-alone server for testing purposes; it serves a directory of netCDF files (using the built-in netCDF handler).

For files larger than approximately 100MB, I run into an issue with reshaping the data (traceback appended below).
It looks like the server serves the data in blocks of a certain size (going by the various generators and yield statements), limiting the block size. In the netCDF handler, however, the data is converted to the *expected* shape (as deduced from the dimensions), which is larger than the block size for certain files. This results in NumPy throwing a ValueError that it can't reshape the array properly.

I've prepended some simple debugging output just before the traceback, which prints out some information on the variable in `handlers.netcdf:LazyVariable.__getitem__`. Judging from that and the  traceback, it shows the array block is limited to 33553440 items, or a shape of (2589, 90, 144), while the full dataset is of shape (2880, 90, 144), and `__getitem__` tries to convert the former into the latter.

I have no problem with opening the dataset using `netCDF4.Dataset` directly (which is also the dataset opener / `netcdf_file` alias used here.

Am I using or interpreting this incorrectly?
If not, is there, as a work-around, a way to increase the block size? (I would guess the actual solution requires more work in the generators and/or `__getitem__`).
Or is it as simple as that the built-in server is not to be used for large-ish files? (I hope not, since it makes developing and testing more complex.)

----

```python
path, key, dtype, _reshape: lon_bnds (slice(0, 144, 1), slice(0, 2, 1)) float64 (144, 2)
actual shape of data block: (144, 2)
path, key, dtype, _reshape: lat_bnds (slice(0, 90, 1), slice(0, 2, 1)) float64 (90, 2)
actual shape of data block: (90, 2)
path, key, dtype, _reshape: time_bnds (slice(0, 2880, 1), slice(0, 2, 1)) float64 (2880, 2)
actual shape of data block: (2880, 2)
path, key, dtype, _reshape: average_DT (slice(0, 2880, 1),) float64 (2880,)
actual shape of data block: (2880,)
path, key, dtype, _reshape: pr (slice(0, 2589, 1), slice(0, 90, 1), slice(0, 144, 1)) float32 (2880, 90, 144)
actual shape of data block: (2589, 90, 144)

[2019-01-08 14:26:52 +0100] [45025] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 181, in handle_request
    for item in respiter:
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydap/responses/dods.py", line 73, in __iter__
    for block in dods(self.dataset):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydap/responses/dods.py", line 86, in _structuretype
    for block in dods(child):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydap/responses/dods.py", line 86, in _structuretype
    for block in dods(child):
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydap/responses/dods.py", line 221, in _basetype
    for block in data:
  File "/usr/local/lib/python3.7/site-packages/numpy/lib/arrayterator.py", line 215, in __iter__
    yield self.var[slice_]
  File "/usr/local/Cellar/python/3.7.2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pydap/handlers/netcdf/__init__.py", line 172, in __getitem__
    .astype(self.dtype).reshape(self._reshape))
ValueError: cannot reshape array of size 33553440 into shape (2880,90,144)
```

**Comment by Juanlu001** [comment]
Python 3.7 had a bug that was fixed in #192. Could you please try again with current `master`? If it still fails, could you please share the file so I can try to reproduce the issue? I'm interested in this problem.

**Comment by Juanlu001** [comment]
I think I am experiencing this same error with a variety of datasets (Linux, python 3.7.3, latest pydap `master`). I will post here if I reach any conclusion.

**Comment by Juanlu001** [comment]
Possible upstream issues:

* https://github.com/Unidata/netcdf4-python/issues/814
* https://github.com/Unidata/netcdf4-python/issues/753

**Comment by Juanlu001** [comment]
In my particular case, the culprit seems to be in `.buf_size` of the `Arrayterator` created by pydap not being equivalent to the multiplication of the dimensions:

```
> /home/juanlu/.pyenv/versions/dap37-debug/lib/python3.7/site-packages/numpy/lib/arrayterator.py(193)__iter__()
-> count = self.buf_size or reduce(mul, self.shape)
(Pdb) p self
<numpy.lib.arrayterator.Arrayterator object at 0x7f8bbde546d8>
(Pdb) p self.buf_size
67108864
(Pdb) p self.shape
(8, 2041, 4320)
(Pdb) p reduce(mul, self.shape)
70536960
```

which then produces an "incomplete" slice:

https://github.com/numpy/numpy/blob/7ebbc2ed3b4a388dd3942e1d8ef2de18074a09b3/numpy/lib/arrayterator.py#L192-L211

And ends up demanding a reshape that can't be performed. More details to follow.

**Comment by Juanlu001** [comment]
Well, it turns out it was in front of our eyes.

Large-ish means... exactly larger than the default buffer size:

https://github.com/pydap/pydap/blob/797aa179f23c42c9acae89ef3416d5d8f0723de2/src/pydap/handlers/lib.py#L38

I confirm that increasing that hardcoded value fixes the issue. I am not an expert in WSGI, but I guess there is a better way of configuring it using the request environ:

https://github.com/pydap/pydap/blob/797aa179f23c42c9acae89ef3416d5d8f0723de2/src/pydap/handlers/lib.py#L102

**Comment by Juanlu001** [comment]
Well, sadly increasing the buffer size fixed some problems, but not all. Now I can at least query the data for its full size, but there is still some index computation that is producing wrong slices. That will have to wait for another day...

**Comment by evertrol** [comment]
I've just been trying, and it looks like I can confirm this is still an issue. If not the buffer size, then indeed the slice computation size:
```
ValueError: cannot reshape array of size 33547200 into shape (1872,145,192)
```

For what it's worth, this is with several files, which are also standard CMIP5 datasets.

**Comment by neaptide** [comment]
Yep, this is a slicing problem.  I can confirm that this happens consistently for both the ascii and dods responses ending in the same `ValueError: cannot reshape array of size 16 into shape (5227,)` at the same point in code (line 177 of `handlers/netcdf/__init__.py`) but only when a variable is subindexed.  It functions as expected when the variable is not subset.  

For example, this works and there is NO error:
`http://whewell.marine.unc.edu/dods/nccoos/level1/b1/ctd1/b1_ctd1_2018_04.nc.ascii?wtemp` 

But this fails:
`http://whewell.marine.unc.edu/dods/nccoos/level1/b1/ctd1/b1_ctd1_2018_04.nc.ascii?wtemp[0:15]` 

resulting in truncated response and no data

```
Dataset {
    Grid {
        Array:
            Float32 wtemp[ntime = 16];
        Maps:
            Int32 ntime[ntime = 16];
    } wtemp;
} b1_ctd1_2018_04%2Enc;
---------------------------------------------
wtemp.wtemp
```

and looking in /var/log/apache2/error.log

```
 mod_wsgi (pid=25243): Exception occurred processing WSGI script '/var/www/pydap/pydap.wsgi'.
 Traceback (most recent call last):
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/pydap/responses/ascii.py", line 42, in __iter__
     for line in ascii(self.dataset):
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/pydap/responses/ascii.py", line 71, in _structuretype
     for line in ascii(child, printname):
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/pydap/responses/ascii.py", line 71, in _structuretype
     for line in ascii(child, printname):
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/pydap/responses/ascii.py", line 85, in _basetype
     for indexes, value in zip(np.ndindex(var.shape), var.data.flat):
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/numpy/lib/arrayterator.py", line 166, in flat
     for block in self:
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/numpy/lib/arrayterator.py", line 215, in __iter__
     yield self.var[slice_]
   File "/opt/env/haines/pydap/lib/python2.7/site-packages/pydap/handlers/netcdf/__init__.py", line 177, in __getitem__
     .astype(self.dtype).reshape(self._reshape))
 ValueError: cannot reshape array of size 16 into shape (5227,)
```

I can share the dods response example and error.log if needed. 

A small change to line 177 in the commit ["do not reshape"](https://github.com/jblarsen/pydap/commit/1a46d93f9810b394e8616ee8e17b6df843bc1efc) applied by @jblarsen resolved the problem for me but might not be the intended/designed return for other cases.  So if you use the example web link ascii response, used in the example above, it is now "fixed" as is the dods response.

Finally, instead of starting a new issue,  I wanted to keep my comment with the general trend of the this issue as it is very important, but maybe the subject line can be changed to better reflect the ValueError and reshape issue.
