### ISSUE TITLE
pydap.exceptions.ExtensionNotSupportedError: 'No handler available for file'

### ISSUE THREAD

**Issue by albertotb** [pydap/pydap#197]
I'm running a server with

    pydap --data ./netcdf/ --port 8001

I put the test file [](http://test.opendap.org/dap/data/nc/coads_climatology.nc) inside the `./netcdf` dir. However, when I try to access the file with

    open_url('http://localhost:8001/coads_climatology.nc')

I get the following error in the server:

```
[2019-06-17 12:49:34 +0200] [30621] [ERROR] Error handling request /coads_climatology.nc.dds
Traceback (most recent call last):
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pydap/wsgi/app.py", line 184, in __call__
    return req.get_response(self.app)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/webob/request.py", line 1314, in send
    application, catch_exc_info=False)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/webob/request.py", line 1278, in call_application
    app_iter = application(self.environ, start_response)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/webob/dec.py", line 129, in __call__
    resp = self.call_func(req, *args, **kw)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/webob/dec.py", line 193, in call_func
    return self.func(req, *args, **kwargs)
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pydap/wsgi/app.py", line 86, in __call__
    app = ServerSideFunctions(get_handler(base, self.handlers))
  File "/home/alberto/anaconda3/lib/python3.7/site-packages/pydap/handlers/lib.py", line 75, in get_handler
    'No handler available for file {filepath}.'.format(filepath=filepath))
pydap.exceptions.ExtensionNotSupportedError: 'No handler available for file /home/alberto/netcdf/coads_climatology.nc.'
```

I have the NetCDF handler installed and also 

    open_url('http://test.opendap.org/dap/data/nc/coads_climatology.nc')

runs just fine

**Comment by Juanlu001** [comment]
@albertotb the original issue was https://github.com/pydap/pydap/issues/129, which was fixed in https://github.com/pydap/pydap/pull/179. Until there is a new release, you will have to install directly from `master`:

https://github.com/pydap/pydap/pull/179#issuecomment-460425196

**Comment by albertotb** [comment]
@Juanlu001 I see. I will install from master and report back

**Comment by albertotb** [comment]
Seems that installing from master fixed the issue, but only needed the repo pydap.handlers.netcdf

**Comment by mhaberler** [comment]
I found that currently using a specific gunicorn version helps: 

```
pip install gunicorn==19.9
```
