### ISSUE TITLE
handlers csv (SequenceType) return exception with a projection selection

### ISSUE THREAD

**Issue by LucaFibbi** [pydap/pydap#199]
When I make a request to a file csv with a projection selection the server throw the following exception:

Traceback (most recent call last):
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/responses/ascii.py", line 38, in __iter__
    for line in dds(self.dataset):
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/responses/dds.py", line 56, in _
    for line in dds(child, level+1, sequence):
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/responses/dds.py", line 65, in _sequencetype
    for line in dds(child, level+1, sequence+1):
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/responses/dds.py", line 109, in _basetype
    type=NUMPY_TO_DAP2_TYPEMAP[var.dtype.char],
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/model.py", line 266, in dtype
    return self.data.dtype
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/handlers/lib.py", line 318, in dtype
    return array_dtype(next(iter(self)), self.template)
  File "/var/www/pydapenv/lib/python3.6/site-packages/pydap/handlers/lib.py", line 442, in out
    return function(row)
IndexError: tuple index out of range
[pid: 1355|app: 0|req: 1/1] 192.168.1.85 () {32 vars in 615 bytes} [Tue Jul  2 14:42:35 2019] GET /obs/test.csv.ascii?sequence.Temperature => generated 25 bytes in 25 msecs (HTTP/1.1 200) 4 headers in 168 bytes (2 switches on core 0)

The first line of test.csv file contain the following variables in this order:
'Datetime', 'Name', 'Lat', 'Lon', 'WindSpeed', 'WindDirection', 'Temperature', 'Humidity', 'Pressure'

I checked the code and I insert some debug print in pydap/handlers/lib.py in the function IterData.__getitem__ and deep_map. The code of this functions with the print is:

```
    def __getitem__(self, key):
        print("DEBUG __getitem__ key ",key)
        out = copy.copy(self)

        # return a child, and adjust the data so that only the corresponding
        # column is returned
        if isinstance(key, string_types):
            print("DEBUG __getitem__ string_types")
            try:
                col = list(self.template._all_keys()).index(key)
            except ValueError:
                raise KeyError(key)
            out.level += 1
            out.template = out.template[key]
            print("DEBUG __getitem__ deep_map(",operator.itemgetter(col),",",out.level,") col",col)
            out.imap.append(deep_map(operator.itemgetter(col), out.level))

        # return a new sequence with the selected children
        elif isinstance(key, list):
            print("DEBUG __getitem__ list")
            cols = [list(self.template.keys()).index(k) for k in key]
            print("DEBUG __getitem__ cols ",cols)
            out.imap.append(deep_map(
                lambda row: tuple(row[i] for i in cols), out.level+1))

        # slice the data
        elif isinstance(key, (int, slice)):
            print("DEBUG __getitem__ slice")
            if isinstance(key, int):
                out.islice.append(slice(key, key+1))
            else:
                out.islice.append(key)

        # filter the data; like slicing it, we can use ``itertools.ifilter``
        # only if the selection is applied to the outermost sequence, otherwise
        # we need to do a deep map
        elif isinstance(key, ConstraintExpression):
            print("DEBUG __getitem__ ConstraintExpression")
            f, m = build_filter(key, self.template)
            out.ifilter.append(f)
            out.imap.append(m)

        else:
            raise KeyError(key)

        return out
```

```
def deep_map(function, level):
    """Map a function inside a nested list, returning the modified data."""
    def out(row, level=level):
        print("DEBUG deep_map.out(",row,",",level,") function",function)
        if level == 1:
            print("DEBUG deep_map.out function(row)=",function(row))
            return function(row)
        else:
            return [out(value, level-1) for value in row]
    print("DEBUG deep_map(",function,",",level,")")
    return out
```

I tested the exception with the script:

```
from pydap.handlers.csv import CSVHandler
from pydap.handlers.lib import apply_projection
from pydap.responses.ascii import ASCIIResponse
from pydap.parsers import parse_projection

test = CSVHandler('/var/www/pydap/obs/test.csv')

print("DEBUG test_csvhandler ",test.dataset['sequence'])
response = ASCIIResponse(apply_projection(parse_projection('sequence.Temperature'),test.dataset))
for line in response:
	print("DEBUG test_csvhandler ",line.decode('ascii'), end = '')
```

The output of the test program is:

DEBUG __getitem__ key  Datetime
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(0) , 1 ) col 0
DEBUG deep_map( operator.itemgetter(0) , 1 )
DEBUG __getitem__ key  Name
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(1) , 1 ) col 1
DEBUG deep_map( operator.itemgetter(1) , 1 )
DEBUG __getitem__ key  Lat
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(2) , 1 ) col 2
DEBUG deep_map( operator.itemgetter(2) , 1 )
DEBUG __getitem__ key  Lon
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(3) , 1 ) col 3
DEBUG deep_map( operator.itemgetter(3) , 1 )
DEBUG __getitem__ key  WindSpeed
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(4) , 1 ) col 4
DEBUG deep_map( operator.itemgetter(4) , 1 )
DEBUG __getitem__ key  WindDirection
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(5) , 1 ) col 5
DEBUG deep_map( operator.itemgetter(5) , 1 )
DEBUG __getitem__ key  Temperature
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(6) , 1 ) col 6
DEBUG deep_map( operator.itemgetter(6) , 1 )
DEBUG __getitem__ key  Humidity
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(7) , 1 ) col 7
DEBUG deep_map( operator.itemgetter(7) , 1 )
DEBUG __getitem__ key  Pressure
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(8) , 1 ) col 8
DEBUG deep_map( operator.itemgetter(8) , 1 )
DEBUG test_csvhandler  <SequenceType with children 'Datetime', 'Name', 'Lat', 'Lon', 'WindSpeed', 'WindDirection', 'Temperature', 'Humidity', 'Pressure'>
DEBUG __getitem__ key  ['Temperature']
DEBUG __getitem__ list
DEBUG __getitem__ cols  [6]
DEBUG deep_map( <function IterData.__getitem__.<locals>.<lambda> at 0x7f9e2ea1bbf8> , 1 )
DEBUG __getitem__ key  Temperature
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(6) , 1 ) col 6
DEBUG deep_map( operator.itemgetter(6) , 1 )
DEBUG __getitem__ key  Temperature
DEBUG __getitem__ string_types
DEBUG __getitem__ deep_map( operator.itemgetter(6) , 1 ) col 6
DEBUG deep_map( operator.itemgetter(6) , 1 )
DEBUG test_csvhandler  Dataset {
DEBUG test_csvhandler      Sequence {
DEBUG deep_map.out( [20160809000020.0, 'MEII', 42.3696, 9.9181, 4.44, 49.0, 24.29, 76.0, 994.0] , 1 ) function <function IterData.__getitem__.<locals>.<lambda> at 0x7f9e2ea1bbf8>
DEBUG deep_map.out function(row)= (24.29,)
DEBUG deep_map.out( (24.29,) , 1 ) function operator.itemgetter(6)
Traceback (most recent call last):
  File "test_csvhandler.py", line 10, in <module>
    for line in response:
  File "/home/operativo/pydap/src/pydap/responses/ascii.py", line 38, in __iter__
    for line in dds(self.dataset):
  File "/home/operativo/pydap/src/pydap/responses/dds.py", line 56, in _
    for line in dds(child, level+1, sequence):
  File "/home/operativo/pydap/src/pydap/responses/dds.py", line 65, in _sequencetype
    for line in dds(child, level+1, sequence+1):
  File "/home/operativo/pydap/src/pydap/responses/dds.py", line 109, in _basetype
    type=NUMPY_TO_DAP2_TYPEMAP[var.dtype.char],
  File "/home/operativo/pydap/src/pydap/model.py", line 266, in dtype
    return self.data.dtype
  File "/home/operativo/pydap/src/pydap/handlers/lib.py", line 323, in dtype
    return array_dtype(next(iter(self)), self.template)
  File "/home/operativo/pydap/src/pydap/handlers/lib.py", line 454, in out
    print("DEBUG deep_map.out function(row)=",function(row))
IndexError: tuple index out of range

I noticed that the index of selected variable stay equal to the original row of data (6), also when the row of data is reduced with the only selected variables generating index out of range.

**Comment by LucaFibbi** [comment]
The following patch avoids the exception:
'''
Index: src/pydap/handlers/lib.py
===================================================================
--- src/pydap/handlers/lib.py	(revision 584)
+++ src/pydap/handlers/lib.py	(working copy)
@@ -347,10 +347,13 @@
         # return a child, and adjust the data so that only the corresponding
         # column is returned
         if isinstance(key, string_types):
-            try:
-                col = list(self.template._all_keys()).index(key)
-            except ValueError:
-                raise KeyError(key)
+            if self.template.keylist is None:
+                try:
+                    col = list(self.template._all_keys()).index(key)
+                except ValueError:
+                    raise KeyError(key)
+            else:
+                col = self.template.keylist.index(key)
             out.level += 1
             out.template = out.template[key]
             out.imap.append(deep_map(operator.itemgetter(col), out.level))
@@ -358,9 +361,9 @@
         # return a new sequence with the selected children
         elif isinstance(key, list):
             cols = [list(self.template.keys()).index(k) for k in key]
-            out.template._visible_keys = key
             out.imap.append(deep_map(
                 lambda row: tuple(row[i] for i in cols), out.level+1))
+            out.template.keylist=key
 
         # slice the data
         elif isinstance(key, (int, slice)):
Index: src/pydap/model.py
===================================================================
--- src/pydap/model.py	(revision 584)
+++ src/pydap/model.py	(working copy)
@@ -258,7 +258,7 @@
         self._shape = ()
 
     def __repr__(self):
-        return '<%s with data %s>' % (type(self).__name__, repr(self.data))
+        return '<%s with data %s dtype %s>' % (type(self).__name__, repr(self.data), repr(self.dtype))
 
     @property
     def dtype(self):
@@ -620,6 +620,7 @@
     def __init__(self, name='nameless', data=None, attributes=None, **kwargs):
         super(SequenceType, self).__init__(name, attributes, **kwargs)
         self._data = data
+        self.keylist = None
 
     def _set_data(self, data):
         self._data = data
@@ -697,6 +698,7 @@
     def __shallowcopy__(self):
         out = type(self)(self.name, self.data, self.attributes.copy())
         out.id = self.id
+        out.keylist = self.keylist
         return out

'''

**Comment by LucaFibbi** [comment]
The following patch avoids the exception:

```
Index: src/pydap/handlers/lib.py
===================================================================
--- src/pydap/handlers/lib.py	(revision 584)
+++ src/pydap/handlers/lib.py	(working copy)
@@ -347,10 +347,13 @@
         # return a child, and adjust the data so that only the corresponding
         # column is returned
         if isinstance(key, string_types):
-            try:
-                col = list(self.template._all_keys()).index(key)
-            except ValueError:
-                raise KeyError(key)
+            if self.template.keylist is None:
+                try:
+                    col = list(self.template._all_keys()).index(key)
+                except ValueError:
+                    raise KeyError(key)
+            else:
+                col = self.template.keylist.index(key)
             out.level += 1
             out.template = out.template[key]
             out.imap.append(deep_map(operator.itemgetter(col), out.level))
@@ -358,9 +361,9 @@
         # return a new sequence with the selected children
         elif isinstance(key, list):
             cols = [list(self.template.keys()).index(k) for k in key]
-            out.template._visible_keys = key
             out.imap.append(deep_map(
                 lambda row: tuple(row[i] for i in cols), out.level+1))
+            out.template.keylist=key
 
         # slice the data
         elif isinstance(key, (int, slice)):

Index: src/pydap/model.py
===================================================================
--- src/pydap/model.py	(revision 584)
+++ src/pydap/model.py	(working copy)
@@ -258,7 +258,7 @@
         self._shape = ()
 
     def __repr__(self):
-        return '<%s with data %s>' % (type(self).__name__, repr(self.data))
+        return '<%s with data %s dtype %s>' % (type(self).__name__, repr(self.data), repr(self.dtype))
 
     @property
     def dtype(self):
@@ -620,6 +620,7 @@
     def __init__(self, name='nameless', data=None, attributes=None, **kwargs):
         super(SequenceType, self).__init__(name, attributes, **kwargs)
         self._data = data
+        self.keylist = None
 
     def _set_data(self, data):
         self._data = data
@@ -697,6 +698,7 @@
     def __shallowcopy__(self):
         out = type(self)(self.name, self.data, self.attributes.copy())
         out.id = self.id
+        out.keylist = self.keylist
         return out
```
