### ISSUE TITLE
Accesssing restricted data set from MERRA2: Unable to parse token: -128][lon

### ISSUE THREAD

**Issue by anthonyatDLR** [pydap/pydap#216]
Hello GitHub Users,

I was hoping one of you clever programmers/scientists could help me overcome an issue with my python code. This is my first time asking a question on the repository, so please let me know if I should provide more detail.

I would like to access MERRA 2 data using a python script. In particular, I would like to access temperature (T2M,TS), pressure (SLP,PS), humidity (QV2M) and wind speed (U2M,V2M) from the M2I1NXASM.5.12.4 product. Eventually I'd like to automate this process so I could download an entire year (or more) for several locations on Earth.

Using the subset tool from NASA GES DISC, I get a list of urls that link to days of data. For example:
https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2I1NXASM.5.12.4/1990/01/MERRA2_100.inst1_2d_asm_Nx.19900101.nc4.nc4?PS[0:23][128:130][498:499],QV2M[0:23][128:130][498:499],SLP[0:23][128:130][498:499],T2M[0:23][128:130][498:499],U2M[0:23][128:130][498:499],V2M[0:23][128:130][498:499],time,lat[128:130],lon[498:499]

I've found that I need to remove the extra .nc4 to access the information set. If I also remove the text from the question mark (?), I can download the full set of data. So the url from above would be:
https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2I1NXASM.5.12.4/1990/01/MERRA2_100.inst1_2d_asm_Nx.19900101.nc4

This downloads the entire data set (all times, latitudes and longitudes for all properties) for a single day. I can then extract the relevant property for the relevant latitude and longitude. This is great, but takes a very long time and provides a large amount of information that I do not keep.

I would like to restrict the amount of data I download with each call to specific properties and just a small range of latitude and longitude. This is done, I believe, with the text following the question mark:
?PS[0:23][128:130][498:499],QV2M[0:23][128:130][498:499],SLP[0:23][128:130][498:499],T2M[0:23][128:130][498:499],U2M[0:23][128:130][498:499],V2M[0:23][128:130][498:499],time,lat[128:130],lon[498:499]

Unfortunately, when I include this I encounter an error. The final portion of the error is:
File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\__init__.py", line 182, in consume
    raise Exception("Unable to parse token: %s" % self.buffer[:10])
Exception: Unable to parse token: -128][lon 

The script (with username, password and directory info redacted) follows, with the error immediately after.

I would appreciate any expertise you could provide on this problem.

All the best,
Anthony

SCRIPT:
from pydap.client import open_url
from pydap.cas.urs import setup_session
import numpy as np

# Credentials
username = 'xxxx'
password = 'xxxx'
# Define the date of interest
year_str = '1990'
month_str = '01'
day_str = '01'
# Create the url string without the data restriction
dataset_url = 'https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2I1NXASM.5.12.4/' + year_str + '/' + \
              month_str + '/MERRA2_100.inst1_2d_asm_Nx.' + year_str + month_str + day_str + '.nc4'
# Access the full data set
session = setup_session(username, password, check_url=dataset_url)
dataset = open_url(dataset_url, session=session)
print(dataset.keys())
time_data = np.squeeze(dataset['time'].data)
print(time_data)
ts_data = np.squeeze(dataset['TS'][:, 129, 498].data)
print(ts_data)
# Create the url string with the data restriction
data_restriction = '?PS[0:23][129][498],QV2M[0:23][129][498],SLP[0:23][129][498],T2M[0:23][129][498],TS[0:23][129][498],U2M[0:23][129][498],V2M[0:23][129][498],time,lat[129],lon[498]'
dataset_url_w_restr = 'https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2I1NXASM.5.12.4/' + year_str + '/' + \
              month_str + '/MERRA2_100.inst1_2d_asm_Nx.' + year_str + month_str + day_str + '.nc4' + data_restriction
# Access the restricted data set
session_restr = setup_session(username, password, check_url=dataset_url_w_restr)
dataset_restr = open_url(dataset_url_w_restr, session=session_restr)
print(dataset_restr.keys())
time_data_restr = np.squeeze(dataset_restr['time'].data)
print(time_data_restr)
ts_data_restr = np.squeeze(dataset_restr['TS'][:, 0, 0].data)
print(ts_data_restr)

OUTPUT INCLUDING ERROR:
C:\ProgramData\Anaconda3\envs\DLR\python.exe C:/Users/XXXX/PycharmProjects/DLR/nasa_error_demo.py
KeysView(<DatasetType with children 'U2M', 'TROPT', 'TROPPB', 'T2M', 'TQL', 'TOX', 'PS', 'V50M', 'DISPH', 'TO3', 'TS', 'T10M', 'TROPPT', 'TQI', 'SLP', 'TQV', 'V2M', 'TROPQ', 'V10M', 'U50M', 'U10M', 'QV2M', 'TROPPV', 'QV10M', 'lat', 'lon', 'time'>)
[   0   60  120  180  240  300  360  420  480  540  600  660  720  780
  840  900  960 1020 1080 1140 1200 1260 1320 1380]
[314.51825 319.3227  322.8298  325.1803  326.41537 326.3942  324.8981
 321.95886 318.22754 313.37582 307.57812 306.38336 305.75992 305.10294
 304.19434 303.2951  302.32877 301.37997 300.59784 299.98468 299.4251
 300.1029  303.5722  310.18658]
KeysView(<DatasetType with children 'U2M', 'T2M', 'PS', 'TS', 'SLP', 'V2M', 'QV2M', 'lat', 'lon', 'time'>)
[   0   60  120  180  240  300  360  420  480  540  600  660  720  780
  840  900  960 1020 1080 1140 1200 1260 1320 1380]
Traceback (most recent call last):
  File "C:/Users/raws_an/PycharmProjects/DLR/nasa_error_demo.py", line 33, in <module>
    ts_data_restr = np.squeeze(dataset_restr['TS'][:, 0, 0].data)
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\model.py", line 320, in __getitem__
    out.data = self._get_data_index(index)
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\model.py", line 349, in _get_data_index
    return self._data[index]
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\handlers\dap.py", line 147, in __getitem__
    dataset = build_dataset(dds)
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\dds.py", line 157, in build_dataset
    return DDSParser(dds).parse()
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\dds.py", line 48, in parse
    var = self.declaration()
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\dds.py", line 68, in declaration
    return method()
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\dds.py", line 77, in base
    shape, dimensions = self.dimensions()
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\dds.py", line 95, in dimensions
    token = self.consume(r'\d+')
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\dds.py", line 37, in consume
    token = super(DDSParser, self).consume(regexp)
  File "C:\ProgramData\Anaconda3\envs\DLR\lib\site-packages\pydap\parsers\__init__.py", line 182, in consume
    raise Exception("Unable to parse token: %s" % self.buffer[:10])
Exception: Unable to parse token: -128][lon 

Process finished with exit code 1

**Comment by pmreyes2** [comment]
I believe the problem here is a bad slice translation from the URL, when the start is different than 0
The notation to download a slice of a variable is url?variable[start:step:stop] when opening the url using pydap open_url it should create the following slice: slice(start,stop+1, step), but instead it generates the slice: slice(start, stop-start+1,step)
What I tried was the slice [305:316] in the url and it came with the following slice: slice(305, 12, 1)
so when I read the variable I also get a similar error:
Exception: Unable to parse token: -293][lon 
I will try to investigate this issue a little bit further...

**Comment by pmreyes2** [comment]
I have find a workaround: Forcing the slice to be the correct one before accessing the data:
Example: Obtaining a slice of a variable in a MERRA2 data file:
```
from pydap.client import open_url
from pydap.cas.urs import setup_session
dataset_url = ('https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/'
               'M2T1NXSLV.5.12.4/2010/04/MERRA2_300.tavg1_2d_slv_Nx.20100401.nc4'
               '?lat[10:1:14]'
              )
session = setup_session(username, password, check_url=dataset_url)
ds = open_url(dataset_url, session=session)
```
The slice for this dataset should be slice(10,15,1) but instead the slice generated is slice(10,5,1). Inspecting ds['lat'] 
`>>> ds['lat']`

`<BaseType with data BaseProxy('https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/2010/04/MERRA2_300.tavg1_2d_slv_Nx.20100401.nc4', 'lat', dtype('>f8'), (5,), (slice(10, 5, 1),))>`

That has as a consequence an error when trying to access the data:
`>>> ds['lat'][:]`

```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-43-3f62dafed39d> in <module>
----> 1 ds5['lat'][:]

~/envs/py38/lib/python3.8/site-packages/pydap/model.py in __getitem__(self, index)
    318     def __getitem__(self, index):
    319         out = copy.copy(self)
--> 320         out.data = self._get_data_index(index)
    321         return out
    322 
...
~/envs/py38/lib/python3.8/site-packages/pydap/parsers/__init__.py in consume(self, regexp)
    180             self.buffer = self.buffer[len(token):]
    181         else:
--> 182             raise Exception("Unable to parse token: %s" % self.buffer[:10])
    183         return token

Exception: Unable to parse token: -5];
} MER
```

A workaround that I have found is to modify the slice to what it should be:
`>>> ds['lat'].data.slice = (slice(10,15,1),)`
Now the dataset has the correct slice slice(10,15,1):
`>>> ds['lat']`

`<BaseType with data BaseProxy('https://goldsmr4.gesdisc.eosdis.nasa.gov/opendap/MERRA2/M2T1NXSLV.5.12.4/2010/04/MERRA2_300.tavg1_2d_slv_Nx.20100401.nc4', 'lat', dtype('>f8'), (5,), (slice(10, 15, 1),))>`

And now there is no error when accessing the data:
`>>> ds['lat'][:]`

`<BaseType with data array([-85. , -84.5, -84. , -83.5, -83. ])>`

I hope this helps, and gets fixed at some point.
