### ISSUE TITLE
documentation build fails

### ISSUE THREAD

**Issue by captainkirk99** [pydap/pydap#252]
The documentation build fails:

 ```
make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v4.4.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/ed/anaconda3/lib/python3.8/site-packages/sphinx/config.py", line 340, in eval_config_file
    exec(code, namespace)
  File "/home/ed/p1/docs/conf.py", line 16, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

make: *** [Makefile:33: html] Error 2
```

**Comment by captainkirk99** [comment]
OK, the answer is to explicitly install sphinx_rtd_theme:

`pip install sphinx_rtd_theme
`
Then the make html works.

**Comment by captainkirk99** [comment]
OK, the answer is to explicitly install sphinx_rtd_theme:

`pip install sphinx_rtd_theme
`
Then the make html works.
