### ISSUE TITLE
pydap tests fail on macos for python >= 3.8

### ISSUE THREAD

**Issue by captainkirk99** [pydap/pydap#256]
```
Traceback (most recent call last):
119
  File "<string>", line 1, in <module>
120
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
121
    exitcode = _main(fd, parent_sentinel)
122
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
123
    self = reduction.pickle.load(from_parent)
124
  File "/Users/runner/work/pydap/pydap/src/pydap/model.py", line 238, in __getattr__
125
    return self.attributes[attr]
126
  File "/Users/runner/work/pydap/pydap/src/pydap/model.py", line 238, in __getattr__
127
    return self.attributes[attr]
128
  File "/Users/runner/work/pydap/pydap/src/pydap/model.py", line 238, in __getattr__
129
    return self.attributes[attr]
130
  [Previous line repeated 993 more times]
131
RecursionError: maximum recursion depth exceeded
132
src/pydap/server/devel_ssl.py F                                          [  3%]
```

**Comment by captainkirk99** [comment]
This happens for python 3.8 and greater. Python 3.7 succeeds in all tests on macos.

**Comment by headtr1ck** [comment]
Same happens on windows with python 3.9

**Comment by aulemahal** [comment]
Same happening on Linux, pydap 3.3.0, python 3.8.13

I am using pydap through xarray, which uses dask to perform parallel computation. The problem arises when using dask in a multi-process configuration and it does not arise when using the multi-threads version.
`Dask`, alike `multiprocessing`, `pickle` to communicate objects between different workers (processes).

Here is an example.
```python3
with dask.config.set(num_workers=2, scheduler='processes'):
    public_url = 'http://psl.noaa.gov/thredds/dodsC/Datasets/ncep.reanalysis/Monthlies/surface/air.mon.ltm.nc'
    ds = xr.open_dataset(
        public_url,
        engine='pydap', user_charset='utf8',
        chunks={'lon': 12}
    )
    mean = ds.air.mean(['lon', 'lat']).load()
```
which fails with:
```python3
---------------------------------------------------------------------------
RecursionError                            Traceback (most recent call last)
File /opt/conda/envs/birdy/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py:632, in dump()
    631 try:
--> 632     return Pickler.dump(self, obj)
    633 except RuntimeError as e:

File /opt/conda/envs/birdy/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py:723, in reducer_override()
    692 """Type-agnostic reducing callback for function and classes.
    693 
    694 For performance reasons, subclasses of the C _pickle.Pickler class
   (...)
    721   https://github.com/cloudpipe/cloudpickle/issues/248
    722 """
--> 723 if sys.version_info[:2] < (3, 7) and _is_parametrized_type_hint(obj):  # noqa  # pragma: no branch
    724     return (
    725         _create_parametrized_type_hint,
    726         parametrized_type_hint_getinitargs(obj)
    727     )

RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

PicklingError                             Traceback (most recent call last)
Cell In [13], line 7
      2 chunks = dict(time=1460, lon=50, lat=50)
      3 ds = xr.open_dataset(
      4     single_ds_url, chunks=chunks,
      5     session=session, engine='pydap',
      6 )
----> 7 tg_mean = ds.tasmax.sel(lat=slice(60, 40), lon=slice(-70, -50)).resample(time='YS').mean().load()

File /opt/conda/envs/birdy/lib/python3.8/site-packages/xarray/core/dataarray.py:1062, in DataArray.load(self, **kwargs)
   1044 def load(self: T_DataArray, **kwargs) -> T_DataArray:
   1045     """Manually trigger loading of this array's data from disk or a
   1046     remote source into memory and return this array.
   1047 
   (...)
   1060     dask.compute
   1061     """
-> 1062     ds = self._to_temp_dataset().load(**kwargs)
   1063     new = self._from_temp_dataset(ds)
   1064     self._variable = new._variable

File /opt/conda/envs/birdy/lib/python3.8/site-packages/xarray/core/dataset.py:735, in Dataset.load(self, **kwargs)
    732 import dask.array as da
    734 # evaluate all the dask arrays simultaneously
--> 735 evaluated_data = da.compute(*lazy_data.values(), **kwargs)
    737 for k, data in zip(lazy_data, evaluated_data):
    738     self.variables[k].data = data

File /opt/conda/envs/birdy/lib/python3.8/site-packages/dask/base.py:600, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    597     keys.append(x.__dask_keys__())
    598     postcomputes.append(x.__dask_postcompute__())
--> 600 results = schedule(dsk, keys, **kwargs)
    601 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File /opt/conda/envs/birdy/lib/python3.8/site-packages/dask/multiprocessing.py:233, in get(dsk, keys, num_workers, func_loads, func_dumps, optimize_graph, pool, initializer, chunksize, **kwargs)
    228 # Note former versions used a multiprocessing Manager to share
    229 # a Queue between parent and workers, but this is fragile on Windows
    230 # (issue #1652).
    231 try:
    232     # Run
--> 233     result = get_async(
    234         pool.submit,
    235         pool._max_workers,
    236         dsk3,
    237         keys,
    238         get_id=_process_get_id,
    239         dumps=dumps,
    240         loads=loads,
    241         pack_exception=pack_exception,
    242         raise_exception=reraise,
    243         chunksize=chunksize,
    244         **kwargs,
    245     )
    246 finally:
    247     if cleanup:

File /opt/conda/envs/birdy/lib/python3.8/site-packages/dask/local.py:511, in get_async(submit, num_workers, dsk, result, cache, get_id, rerun_exceptions_locally, pack_exception, raise_exception, callbacks, dumps, loads, chunksize, **kwargs)
    509         _execute_task(task, data)  # Re-execute locally
    510     else:
--> 511         raise_exception(exc, tb)
    512 res, worker_id = loads(res_info)
    513 state["cache"][key] = res

File /opt/conda/envs/birdy/lib/python3.8/site-packages/dask/local.py:319, in reraise(exc, tb)
    317 if exc.__traceback__ is not tb:
    318     raise exc.with_traceback(tb)
--> 319 raise exc

File /opt/conda/envs/birdy/lib/python3.8/site-packages/dask/multiprocessing.py:118, in pack_exception()
    116 tb = _pack_traceback(exc_traceback)
    117 try:
--> 118     result = dumps((e, tb))
    119 except BaseException as e:
    120     exc_type, exc_value, exc_traceback = sys.exc_info()

File /opt/conda/envs/birdy/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py:73, in dumps()
     69 with io.BytesIO() as file:
     70     cp = CloudPickler(
     71         file, protocol=protocol, buffer_callback=buffer_callback
     72     )
---> 73     cp.dump(obj)
     74     return file.getvalue()

File /opt/conda/envs/birdy/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py:639, in dump()
    634 if "recursion" in e.args[0]:
    635     msg = (
    636         "Could not pickle object as excessively deep recursion "
    637         "required."
    638     )
--> 639     raise pickle.PicklingError(msg) from e
    640 else:
    641     raise

PicklingError: Could not pickle object as excessively deep recursion required.
```

I made my example using dask xarray because I don't know how to replicate the chunking+pickling process without them. When I have more time, I can try to dig deeper and isolate the problem further.
I am using, dask = 2022.11.0 and xarray = 2022.10.0 .

The same issue has been flagged downstream in `xarray` : pydata/xarray#4348.

**Comment by Mikejmnez** [comment]
I recently started working on this and identified the root of it, for which I opened a separate issue #292 . I didn't fully realized it was the same issue as the one here described. While technically a duplicate, I will leave #292 open as I think it clearly explains what it's going on and the potential solutions.

Related to that, I have a temporal patchwork that allows for pydap to continue working on newer python versions on both MacOS and Windows. See PR #293 . All tests pass and looks good, albeit again a temporal solution.

**Comment by Mikejmnez** [comment]
Tests now pass with both macOS (and likely for Windows) with PR #293. There is a broader (pickleing) issue that is the root of the problem, and that is broadly described in #292 in the current version of pydap. I will continue working on that and will leave that issue open. I am closing this issue since the behavior described in the title, that tests fail, is no longer true.
