### ISSUE TITLE
ValueError: buffer size must be a multiple of element size

### ISSUE THREAD

**Issue by ghost** [pydap/pydap#273]
I thought this was a relatively straightforward data pull (because it parallels the main example at https://www.pydap.org/en/latest/client.html quite closely) but I got an error. What am I doing wrong? 
```
from pydap.client import open_dods
url = ('http://psl.noaa.gov/thredds/dodsC/Datasets'+
       '/NARR/monolevel/uwnd.10m.2000.nc')
ds = open_url(url)
uwnd = ds.uwnd
uwnd.shape
(2928, 277, 349)
grid = uwnd[10,10:24,30:37]
C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\handlers\dap.py:397: RuntimeWarning: overflow encountered in int_scalars
  count = response_dtype.itemsize * n
Traceback (most recent call last):

  File "C:\Users\codiga_d\AppData\Local\Temp\ipykernel_15432\2319456804.py", line 1, in <cell line: 1>
    grid = uwnd[10,10:24,30:37]

  File "C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\model.py", line 746, in __getitem__
    var.data = self[var.name].data[slice_]

  File "C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\handlers\dap.py", line 175, in __getitem__
    dataset.data = unpack_data(BytesReader(data), dataset)

  File "C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\handlers\dap.py", line 452, in unpack_data
    return unpack_children(xdr_stream, dataset)

  File "C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\handlers\dap.py", line 383, in unpack_children
    out.append(tuple(unpack_children(stream, col)))

  File "C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\handlers\dap.py", line 387, in unpack_children
    out.extend(convert_stream_to_list(stream, col.dtype, col.shape,

  File "C:\Users\codiga_d\Anaconda3\envs\EQ\lib\site-packages\pydap\handlers\dap.py", line 413, in convert_stream_to_list
    np.frombuffer(

ValueError: buffer size must be a multiple of element size

```

**Comment by Mikejmnez** [comment]
This is an old issue but relevant since I can still produce an error if I follow along, albeit not exactly the same error. BTW, there is no issue with pydap, but rather it relates to a feature of the pydap.model. 
Following the code above still produces an error:
```python
url = 'http://psl.noaa.gov/thredds/dodsC/Datasets/NARR/monolevel/uwnd.10m.2000.nc'
ds = open_url(url)
uwnd = ds['uwnd']
uwnd[10,10:24,30:37]
>>>  IndexError: index 0 is out of bounds for axis 0 with size 0
```
However, the correct way to slice a pydap- dataset for variable `uwnd` is instead and access the data is
```python
uwnd['uwnd'][10,10:24,30:37]
>>> <BaseType with data array([[[-2.025238  , -1.9705505 , -2.493988  , -2.4705505 ,
         -2.0486755 , -2.587738  , -1.947113  ],
        [-2.415863  , -3.1424255 , -3.2361755 , -3.2361755 ,
...
```
Note the extra `['uwnd']`. `xarray` already unpacks a pydap dataset, but under the hood is doing something like this...

I am closing this issue, feel free to re-open.
