### ISSUE TITLE
Diagnose xarray-with-pydap errors described below

### ISSUE THREAD

**Issue by jgallagher59701** [pydap/pydap#297]
In the following cases, I can use PyDAP to read from both the URLs and get data. Performance is not great, but the results come back fast enough.

Example, using the POCLOUD URL:

```
from pydap.client import open_url

url2 = "https://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%200.5%20Degree%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_2017-12_ECCO_V4r4_latlon_0p50deg"
>>> ds2 = open_url(url2)
>>> list(ds2.keys())
['SALT', 'THETA', 'Z_bnds', 'latitude_bnds', 'time_bnds', 'longitude_bnds', 'Z', 'latitude', 'longitude', 'nv', 'time']
>>> lat = ds2['latitude']
>>> lat
<BaseType with data BaseProxy('https://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%200.5%20Degree%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_2017-12_ECCO_V4r4_latlon_0p50deg', 'latitude', dtype('>f4'), (360,), (slice(None, None, None),))>
>>> lat[:]
<BaseType with data array([-89.75, -89.25, -88.75, -88.25, -87.75, -87.25, -86.75, -86.25,
...
        86.25,  86.75,  87.25,  87.75,  88.25,  88.75,  89.25,  89.75],
      dtype=float32)>
>>> 
PyDAP can read the 51MB variable SALT is about 10s. Why xarray gets stuck on this is a problem.
```

### Case 1
```
import netCDF4 as nc
import xarray as xr
from pydap.client import open_url

url2 = "https://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%200.5%20Degree%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_2017-12_ECCO_V4r4_latlon_0p50deg"
xds2 = xr.open_dataset(url2, engine='pydap')
```
Fails with:

```
>>> xds2 = xr.open_dataset(url2, engine='pydap')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/xarray/backends/api.py", line 495, in open_dataset
    backend_ds = backend.open_dataset(
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/xarray/backends/pydap_.py", line 146, in open_dataset

...

  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/pydap/handlers/dap.py", line 357, in unpack_children
    out.extend(convert_stream_to_list(stream, col.dtype, col.shape,
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/pydap/handlers/dap.py", line 383, in convert_stream_to_list
    np.fromstring(
ValueError: string size must be a multiple of element size
```
### Case 2
```
import netCDF4 as nc
import xarray as xr
from pydap.client import open_url

url = 'https://opendap.earthdata.nasa.gov/hyrax/data/nc/fnoc1.nc'
xds = xr.open_dataset(url, engine='pydap')
xds['v'][:]
```
Fails with

```
>>> xds['v'][:]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/xarray/core/common.py", line 151, in __repr__
    return formatting.array_repr(self)
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/xarray/core/formatting.py", line 519, in array_repr
    data_repr = short_data_repr(arr)
...
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/xarray/coding/variables.py", line 70, in __array__
    return self.func(self.array)
  File "/Users/jimg/opt/miniforge3/envs/opendap/lib/python3.9/site-packages/xarray/coding/variables.py", line 219, in _scale_offset_decoding
    data *= scale_factor
numpy.core._exceptions.UFuncTypeError: Cannot cast ufunc 'multiply' output from dtype('<U32') to dtype('float32') with casting rule 'same_kind'
```
while

```
>>> xds['lat']
<xarray.DataArray 'lat' (lat: 17)>
array([50. , 47.5, 45. , 42.5, 40. , 37.5, 35. , 32.5, 30. , 27.5, 25. , 22.5,
       20. , 17.5, 15. , 12.5, 10. ], dtype=float32)
Coordinates:
  * lat      (lat) float32 50.0 47.5 45.0 42.5 40.0 ... 20.0 17.5 15.0 12.5 10.0
Attributes:
    units:    degree North
```
works. the lat variable does not have a scale_factor attribute while v does

**Comment by Mikejmnez** [comment]
# case 1 works fine
I needed to pass the session argument onto `xarray`, but didn't get an error:
```python
url2 = "https://opendap.earthdata.nasa.gov/providers/POCLOUD/collections/ECCO%20Ocean%20Temperature%20and%20Salinity%20-%20Monthly%20Mean%200.5%20Degree%20(Version%204%20Release%204)/granules/OCEAN_TEMPERATURE_SALINITY_mon_mean_2017-12_ECCO_V4r4_latlon_0p50deg"
xds2 = xr.open_dataset(url2, engine='pydap', session=session)
```
where session was defined as in the explanation above, i.e.
```python
session = setup_session(username, password, check_url=hyrax_url) 
```
With that, I was able to read/load data and make plots:
```python
fig, axes = plt.subplots(1,2, figsize=(12, 4))
xds2['SALT'].isel(time=0, Z=0).plot(ax=axes[0]);
xds2['THETA'].isel(time=0, Z=0).plot(ax=axes[1]);
plt.show()
```
produced:

![Screenshot 2024-03-27 at 2 39 18 PM](https://github.com/pydap/pydap/assets/8241481/510f1ee8-4686-427f-b448-280a008abcb0)

**Comment by Mikejmnez** [comment]
# case 2: Issues with metadata type
```python
from pydap.cas.urs import setup_session
from pydap.client import open_url
# setup session info to access EarthData
username = "Username" # Earthdata URS Login (only needed for NGAP Hyrax) Get account here https://urs.earthdata.nasa.gov/
password= "write_password_here"
hyrax_url = 'https://opendap.earthdata.nasa.gov/collections/C2532426483-ORNL_CLOUD/granules/'
session = setup_session(username, password, check_url=hyrax_url)

```



Since `pydap.client.open_url` is the backend for `xarray`, all xarray is doing is extracting the metadata/attributes necessary to `scale`, `add_offsets` and `fill_values` each data variable (e.g. add nans over land values). These parameters are defined in the attributes for each variable but not for dimensions like `time`, `lat` and `lon` because these are 1d arrays.

```python
url = 'https://opendap.earthdata.nasa.gov/hyrax/data/nc/fnoc1.nc'
data = open_url(url, session=session)
data['v'].attributes
>>> {'units': 'meter per second',
         'long_name': 'Vector wind northward component',
          'missing_value': '-32767',
          'scale_factor': '0.005',
          'DODS_Name': 'VWind'}
```
`xarray` can easily decode attributes, but in this case  <ins>the types of 'scale_factor' and `missing_value` are  strings rather than any numeric type</ins>. With `pydap` it is not an issue because there is no decoding in open_url .

## solution: fix the metadata so values are numeric type
Consider the decoding function:

```python
def decode(_DATA, attrs):
    """
    Decoding function
    """
    # default values
    Mask = 1
    scale = 1

    _Fill_value = attrs.pop('missing_value', None)
    scale_factor = attrs.pop('scale_factor', None)

    if scale_factor is not None:
        scale = scale_factor
    if _Fill_value is not None:
        mask = _DATA.ravel() > _Fill_value
        nmask = mask.reshape(np.shape(_DATA))
        Mask = np.reshape(np.where(nmask.ravel()==0, np.nan, nmask.ravel()), np.shape(nmask))

    return Mask, scale
```
I get a similar the error  if I just pass the variable data['v'] and its attributes  when trying to apply an operation between a string and a number
```python
Mask, offset, scale = decode(np.squeeze(data['v'][0,:].data), data['v'].attributes)
>>>
---------------------------------------------------------------------------
UFuncTypeError                            Traceback (most recent call last)
Cell In[54], line 1
----> 1 Mask, offset, scale = decode(np.squeeze(data['v'][0,:].data), data['v'].attributes)

UFuncTypeError: ufunc 'greater' did not contain a loop with signature matching types (<class 'numpy.dtypes.Int16DType'>, <class 'numpy.dtypes.StrDType'>) -> None
```

* Repeat after fixing the attributes types
```python
attrs = data['v'].attributes
attrs['missing_value'] = float(attrs['missing_value'])
attrs['scale_factor'] = float(attrs['scale_factor'])
```
Extract mask and offsets with updated attributes dictionary. NOTE: <ins>there is no longer an error</ins>
```python
Mask, scale = decode(DATA, attrs)
```
This allows to correct and plot data:

```python
Lons, Lats = np.meshgrid(data['lon'][:].data, data['lat'][:].data)

plt.contourf(Lons, Lats, Mask*scale*np.squeeze(data['v'][0, :].data), 200)
plt.colorbar()
plt.show()
```
![Screenshot 2024-03-27 at 3 57 08 PM](https://github.com/pydap/pydap/assets/8241481/13d05c2f-8c7b-4950-99ae-7099d4fdf8a1)




Note that in this case Mask is all ones (there is no masking needed for land value - > atmospheric wind rather than ocean velocities), and `scale=0.005`. Values in the color map are correct.

**Comment by Mikejmnez** [comment]
BTW: Issues with decoding are very common and still being figured out internally within xarray, see [pydata/xarrayPR#6812](https://github.com/pydata/xarray/pull/6812)

**Comment by Mikejmnez** [comment]
I am closing this issue as completed. Feel free to open if necessary
